root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./bin/api ./cmd/api"
  bin = "bin/api"
  include_ext = ["go", "tpl", "tmpl", "html", "sql"]
  exclude_dir = ["assets", "tmp", "vendor", ".git", "bin"]
  delay = 500

[log]
time = true

[run]
cmd = "./bin/api"
